### ISSUE TITLE
Docker image no longer there and local docker run fails to finish

### ISSUE THREAD

**Issue by mattortiz** [techmaturity/techmaturity#46]
Has this project been retired?

**Comment by bbensen** [comment]
The last released public docker image on docker hub seems to be missing now and yes the build from source in the repo has some issues now due to changes in the gem file dependencies to close insecurities.  There is no staff left at TM that supports it but I can accept a merge request if someone can help get it back and running.  Good to hear from you again Matt!

**Comment by iceycake** [comment]
Hi all!!!!  I merged one of the pull requested for a rail upgrade. In addition, https://github.com/techmaturity/techmaturity/pull/50 should fix the missing docker image issue.

Also, please bring on more pull requests to modernize and fix the security issues.
